version: '3.9'

services:
  web-server:
    container_name: "nt-web-server-dev"
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "8000:4000"
    volumes:
      - /app/node_modules
      - .:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - MONGO_USER=admin
      - MONGO_PASSWORD=securepassword
    depends_on:
      - mongo-server
    command: npm run dev
  
  mongo-server:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=securepassword
    volumes:
      - mongo-db-dev-volumne:/data/db

volumes:
  mongo-db-dev-volumne: