version: '3.9'

services:
  web-server:
    container_name: "nt-web-server-prod"
    build: 
      context: .
      args:
        - NODE_ENV=production
    ports:
      - "8000:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - MONGO_USER=admin
      - MONGO_PASSWORD=securepassword
    depends_on:
      - mongo-server
    command: npm run start
  
  mongo-server:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=securepassword
    volumes:
      - mongo-db-prod-volumne:/data/db

volumes:
  mongo-db-prod-volumne: