version: '3.9'

services:
  web-server:
    container_name: "nt-web-server-prod"
    build: 
      context: .
      args:
        - NODE_ENV=production
    ports:
      - "8000:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: npm run start
